application: sellmymusic
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /admin
  script: main.py
  login: admin

- url: /add
  script: main.py
  login: admin

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img